Repository fthomas/fs2-cron, pull requests merged in 2021-03, with the labels that each got.

#184 Update sbt to 1.4.8
  project/build.properties
Labels: dependency-update

#185 Update scalatest to 3.2.6
  project/Dependencies.scala
Labels: dependency-update

#186 Update sbt to 1.4.9
  project/build.properties
Labels: dependency-update

#187 Update sbt-ci-release to 1.5.6
  project/plugins.sbt
Labels: dependency-update

#188 Set versionScheme to "early-semver"
  build.sbt
Labels: build

#191 Use vals for the implementation of ZonedTimer#{now, timer}
  modules/core/src/main/scala/eu/timepit/fs2cron/ZonedTimer.scala
  modules/core/src/test/scala/eu/timepit/fs2cron/FS2CronTest.scala
Labels: refactoring

#192 Update sbt-tpolecat to 0.1.17
  project/plugins.sbt
Labels: dependency-update

#193 Separate streams from Cron4s
  .github/workflows/ci.yml
  .mergify.yml
  README.md
  build.sbt
  modules/core/src/main/scala/eu/timepit/fs2cron/ScheduledStreams.scala
  modules/core/src/main/scala/eu/timepit/fs2cron/Scheduler.scala
  modules/core/src/main/scala/eu/timepit/fs2cron/ZonedTimer.scala
  modules/core/src/main/scala/eu/timepit/fs2cron/package.scala
  modules/core/src/test/scala/eu/timepit/fs2cron/FS2CronTest.scala
  modules/cron4s/src/main/scala/eu/timepit/fs2cron/cron4s/Cron4sScheduler.scala
  modules/cron4s/src/test/scala/eu/timepit/fs2cron/cron4s/Cron4sSchedulerTest.scala
  modules/readme/README.md
  project/plugins.sbt
  scripts/release.sh
Labels: enhancement

#194 Update sbt-ci-release to 1.5.7
  project/plugins.sbt
Labels: dependency-update

#195 Update to fs2 3.0.0-M9
  README.md
  modules/core/src/main/scala/eu/timepit/fs2cron/ScheduledStreams.scala
  modules/core/src/main/scala/eu/timepit/fs2cron/Scheduler.scala
  modules/cron4s/src/main/scala/eu/timepit/fs2cron/cron4s/Cron4sScheduler.scala
  modules/cron4s/src/test/scala/eu/timepit/fs2cron/cron4s/Cron4sSchedulerTest.scala
  modules/readme/README.md
  project/Dependencies.scala
Labels: dependency-update

#197 Update fs2-core to 3.0.0
  project/Dependencies.scala
Labels: dependency-update

#198 Update mdoc_2.13, sbt-mdoc to 2.2.19
  project/plugins.sbt
Labels: dependency-update

#200 Update sbt-scalajs to 1.5.1
  project/plugins.sbt
Labels: dependency-update
